`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:27:42 CST (Apr 24 2022 06:27:42 UTC)

module DFT_compute_NotEQ_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  XOR2XL g14(.A (in2), .B (in1), .Y (out1));
endmodule

