`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 16:17:27 CST (Apr 24 2022 08:17:27 UTC)

module DFT_compute_Add_8U_12_4(in1, out1);
  input [7:0] in1;
  output [7:0] out1;
  wire [7:0] in1;
  wire [7:0] out1;
  wire inc_add_21_2_n_0, inc_add_21_2_n_2, inc_add_21_2_n_4,
       inc_add_21_2_n_6, inc_add_21_2_n_8, inc_add_21_2_n_10;
  INVX1 g4(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_21_2_g67(.A (in1[7]), .B (inc_add_21_2_n_10), .Y
       (out1[7]));
  XNOR2X1 inc_add_21_2_g68(.A (in1[6]), .B (inc_add_21_2_n_8), .Y
       (out1[6]));
  NAND2BX1 inc_add_21_2_g69(.AN (inc_add_21_2_n_8), .B (in1[6]), .Y
       (inc_add_21_2_n_10));
  XNOR2X1 inc_add_21_2_g70(.A (in1[5]), .B (inc_add_21_2_n_6), .Y
       (out1[5]));
  NAND2BX1 inc_add_21_2_g71(.AN (inc_add_21_2_n_6), .B (in1[5]), .Y
       (inc_add_21_2_n_8));
  XNOR2X1 inc_add_21_2_g72(.A (in1[4]), .B (inc_add_21_2_n_4), .Y
       (out1[4]));
  NAND2BX1 inc_add_21_2_g73(.AN (inc_add_21_2_n_4), .B (in1[4]), .Y
       (inc_add_21_2_n_6));
  XNOR2X1 inc_add_21_2_g74(.A (in1[3]), .B (inc_add_21_2_n_2), .Y
       (out1[3]));
  NAND2BX1 inc_add_21_2_g75(.AN (inc_add_21_2_n_2), .B (in1[3]), .Y
       (inc_add_21_2_n_4));
  XNOR2X1 inc_add_21_2_g76(.A (in1[2]), .B (inc_add_21_2_n_0), .Y
       (out1[2]));
  NAND2BX1 inc_add_21_2_g77(.AN (inc_add_21_2_n_0), .B (in1[2]), .Y
       (inc_add_21_2_n_2));
  XOR2XL inc_add_21_2_g78(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_21_2_g79(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_21_2_n_0));
endmodule

