`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 16:17:33 CST (Apr 24 2022 08:17:33 UTC)

module DFT_compute_LeftShift_5S_16_1(in1, out1);
  input [1:0] in1;
  output [4:0] out1;
  wire [1:0] in1;
  wire [4:0] out1;
  wire n_1, n_3;
  assign out1[4] = 1'b0;
  NOR2X1 g30(.A (n_1), .B (n_3), .Y (out1[3]));
  NOR2X1 g33(.A (in1[1]), .B (n_3), .Y (out1[1]));
  NOR2X1 g32(.A (n_1), .B (in1[0]), .Y (out1[2]));
  NOR2X2 g31(.A (in1[1]), .B (in1[0]), .Y (out1[0]));
  CLKINVX12 g35(.A (in1[1]), .Y (n_1));
  CLKINVX3 g34(.A (in1[0]), .Y (n_3));
endmodule

