`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:18:43 CST (Apr 24 2022 03:18:43 UTC)

module DFT_compute_LessThanEQ_4Sx3S_1U_4(in2, in1, out1);
  input [3:0] in2;
  input [2:0] in1;
  output out1;
  wire [3:0] in2;
  wire [2:0] in1;
  wire out1;
  wire lte_21_53_n_0, lte_21_53_n_1, lte_21_53_n_2, lte_21_53_n_3,
       lte_21_53_n_4, lte_21_53_n_5, lte_21_53_n_6, lte_21_53_n_7;
  OAI211X1 lte_21_53_g182(.A0 (lte_21_53_n_1), .A1 (lte_21_53_n_7), .B0
       (lte_21_53_n_4), .C0 (lte_21_53_n_2), .Y (out1));
  OAI211X1 lte_21_53_g183(.A0 (lte_21_53_n_0), .A1 (in1[2]), .B0
       (lte_21_53_n_2), .C0 (lte_21_53_n_6), .Y (lte_21_53_n_7));
  OAI21X1 lte_21_53_g184(.A0 (in2[1]), .A1 (lte_21_53_n_3), .B0
       (lte_21_53_n_5), .Y (lte_21_53_n_6));
  OAI2BB1X1 lte_21_53_g185(.A0N (in2[1]), .A1N (lte_21_53_n_3), .B0
       (in1[1]), .Y (lte_21_53_n_5));
  NAND3X1 lte_21_53_g186(.A (in2[3]), .B (in1[2]), .C (lte_21_53_n_0),
       .Y (lte_21_53_n_4));
  NOR2BX1 lte_21_53_g187(.AN (in2[0]), .B (in1[0]), .Y (lte_21_53_n_3));
  NAND2BX1 lte_21_53_g188(.AN (in1[2]), .B (in2[3]), .Y
       (lte_21_53_n_2));
  NOR2BX1 lte_21_53_g189(.AN (in1[2]), .B (in2[3]), .Y (lte_21_53_n_1));
  INVX1 lte_21_53_g190(.A (in2[2]), .Y (lte_21_53_n_0));
endmodule


