`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:28:42 CST (Apr 24 2022 07:28:42 UTC)

module DFT_compute_LessThan_2Ux8U_1U_4(in2, in1, out1);
  input [1:0] in2;
  input [7:0] in1;
  output out1;
  wire [1:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3;
  OR4X1 gt_21_21_g131(.A (in1[3]), .B (in1[2]), .C (gt_21_21_n_1), .D
       (gt_21_21_n_3), .Y (out1));
  OA21X1 gt_21_21_g132(.A0 (in1[1]), .A1 (gt_21_21_n_0), .B0
       (gt_21_21_n_2), .Y (gt_21_21_n_3));
  OAI2BB1X1 gt_21_21_g133(.A0N (in1[1]), .A1N (gt_21_21_n_0), .B0
       (in2[1]), .Y (gt_21_21_n_2));
  OR4X1 gt_21_21_g134(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gt_21_21_n_1));
  NOR2BX1 gt_21_21_g135(.AN (in1[0]), .B (in2[0]), .Y (gt_21_21_n_0));
endmodule


