`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:25:16 CST (Apr 24 2022 03:25:16 UTC)

module DFT_compute_LessThan_3Ux4U_1U_1(in2, in1, out1);
  input [2:0] in2;
  input [3:0] in1;
  output out1;
  wire [2:0] in2;
  wire [3:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5, gt_21_21_n_6, gt_21_21_n_7;
  wire gt_21_21_n_8, gt_21_21_n_9, gt_21_21_n_10;
  NOR2X1 gt_21_21_g61(.A (gt_21_21_n_8), .B (gt_21_21_n_10), .Y (out1));
  NOR2X1 gt_21_21_g62(.A (gt_21_21_n_1), .B (gt_21_21_n_9), .Y
       (gt_21_21_n_10));
  AOI21X1 gt_21_21_g63(.A0 (gt_21_21_n_6), .A1 (gt_21_21_n_4), .B0
       (gt_21_21_n_5), .Y (gt_21_21_n_9));
  NOR2X1 gt_21_21_g65(.A (in1[3]), .B (gt_21_21_n_7), .Y
       (gt_21_21_n_8));
  NAND2BX1 gt_21_21_g66(.AN (in1[2]), .B (in2[2]), .Y (gt_21_21_n_7));
  NAND2X4 gt_21_21_g67(.A (in1[0]), .B (gt_21_21_n_2), .Y
       (gt_21_21_n_6));
  NOR2X1 gt_21_21_g69(.A (gt_21_21_n_3), .B (in1[1]), .Y
       (gt_21_21_n_5));
  NAND2X2 gt_21_21_g70(.A (in1[1]), .B (gt_21_21_n_3), .Y
       (gt_21_21_n_4));
  CLKINVX4 gt_21_21_g72(.A (in2[1]), .Y (gt_21_21_n_3));
  CLKINVX12 gt_21_21_g74(.A (in2[0]), .Y (gt_21_21_n_2));
  NAND2BX1 gt_21_21_g2(.AN (in1[3]), .B (gt_21_21_n_0), .Y
       (gt_21_21_n_1));
  NAND2BX1 gt_21_21_g75(.AN (in2[2]), .B (in1[2]), .Y (gt_21_21_n_0));
endmodule


