`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:14:00 CST (Apr 24 2022 07:14:00 UTC)

module DFT_compute_entirecomputation_alt5_0(in1, in2, out1);
  input [7:0] in1, in2;
  output [7:0] out1;
  wire [7:0] in1, in2;
  wire [7:0] out1;
  wire n_0, n_1, n_5, n_6, n_7, n_8, n_10, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_19, n_20, n_21;
  wire n_22, n_27, n_29, n_30, n_31, n_33, n_36, n_37;
  wire n_38, n_39, n_40, n_42, n_46, n_49, n_50, n_51;
  wire n_52, n_98, n_100, n_116, n_120, n_121, n_129, n_130;
  wire n_131, n_148, n_150, n_151, n_207, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_219, n_220, n_222;
  MXI2X1 g9401(.A (n_21), .B (n_22), .S0 (n_52), .Y (out1[6]));
  MXI2X1 g9402(.A (n_19), .B (n_20), .S0 (n_51), .Y (out1[5]));
  MXI2XL g9404(.A (n_37), .B (n_38), .S0 (n_49), .Y (out1[3]));
  OAI21X1 g9407(.A0 (n_40), .A1 (n_50), .B0 (n_46), .Y (n_52));
  OAI21X1 g9406(.A0 (n_121), .A1 (n_50), .B0 (n_120), .Y (n_51));
  OAI21XL g9408(.A0 (n_42), .A1 (n_100), .B0 (n_17), .Y (n_49));
  NAND2BX1 g9417(.AN (n_131), .B (n_39), .Y (n_46));
  NOR2X4 g9411(.A (n_42), .B (n_100), .Y (n_50));
  OR2XL g9416(.A (n_33), .B (n_131), .Y (n_40));
  NAND2X1 g9422(.A (n_14), .B (n_30), .Y (n_39));
  INVXL g9426(.A (n_37), .Y (n_38));
  INVXL g9433(.A (n_222), .Y (n_36));
  INVXL g9425(.A (n_129), .Y (n_29));
  NOR2XL g9429(.A (n_212), .B (n_5), .Y (n_27));
  INVXL g9432(.A (n_21), .Y (n_22));
  INVXL g9434(.A (n_19), .Y (n_20));
  NAND2X1 g9430(.A (n_15), .B (n_14), .Y (n_37));
  INVXL g9435(.A (n_12), .Y (n_13));
  NAND2X1 g9431(.A (n_17), .B (n_15), .Y (n_33));
  MXI2X1 g9436(.A (n_0), .B (in1[0]), .S0 (in2[0]), .Y (out1[0]));
  NOR2X1 g9437(.A (n_1), .B (n_8), .Y (n_21));
  NOR2BX1 g9439(.AN (n_7), .B (n_6), .Y (n_19));
  NOR2X2 g9441(.A (n_10), .B (n_6), .Y (n_30));
  INVX1 g9442(.A (n_215), .Y (n_5));
  INVX1 g9451(.A (n_16), .Y (n_14));
  INVX1 g9449(.A (n_1), .Y (n_31));
  XNOR2X1 g9440(.A (in2[7]), .B (in1[7]), .Y (n_12));
  NOR2X1 g9454(.A (in2[6]), .B (in1[6]), .Y (n_1));
  NAND2X4 g9444(.A (in1[3]), .B (in2[3]), .Y (n_15));
  NOR2X4 g9447(.A (in2[4]), .B (in1[4]), .Y (n_10));
  NOR2X4 g9448(.A (in2[5]), .B (in1[5]), .Y (n_6));
  NOR2X8 g9446(.A (in2[2]), .B (in1[2]), .Y (n_42));
  NAND2X6 g9443(.A (in1[5]), .B (in2[5]), .Y (n_7));
  AND2XL g9453(.A (in2[6]), .B (in1[6]), .Y (n_8));
  NAND2X4 g9456(.A (in2[2]), .B (in1[2]), .Y (n_17));
  NOR2X4 g9458(.A (in2[3]), .B (in1[3]), .Y (n_16));
  INVX1 g9459(.A (in1[0]), .Y (n_0));
  MXI2X1 g9465(.A (n_36), .B (n_222), .S0 (n_98), .Y (out1[2]));
  CLKBUFX2 g9478(.A (n_214), .Y (n_98));
  INVX3 g9479(.A (n_116), .Y (n_100));
  XNOR2XL g9483(.A (n_220), .B (n_27), .Y (out1[1]));
  OAI21X4 g9464_dup9487(.A0 (n_212), .A1 (n_220), .B0 (n_215), .Y
       (n_116));
  OAI21XL g9490(.A0 (n_10), .A1 (n_16), .B0 (n_219), .Y (n_120));
  NAND2BX1 g9492(.AN (n_33), .B (n_219), .Y (n_121));
  NOR2BX1 g9495(.AN (n_219), .B (n_10), .Y (n_129));
  AOI21X4 g9497(.A0 (n_130), .A1 (n_7), .B0 (n_6), .Y (n_131));
  NAND2X8 g9469_dup_dup(.A (in2[4]), .B (in1[4]), .Y (n_130));
  MXI2X1 g535(.A (n_12), .B (n_13), .S0 (n_151), .Y (out1[7]));
  OAI21X2 g536(.A0 (n_148), .A1 (n_210), .B0 (n_150), .Y (n_151));
  NAND2X1 g540(.A (n_30), .B (n_31), .Y (n_148));
  OAI21X1 g539(.A0 (n_8), .A1 (n_131), .B0 (n_31), .Y (n_150));
  MXI2XL g537(.A (n_129), .B (n_29), .S0 (n_210), .Y (out1[4]));
  AOI21X2 g155(.A0 (n_207), .A1 (n_214), .B0 (n_209), .Y (n_210));
  NOR2X1 g158(.A (n_42), .B (n_16), .Y (n_207));
  AOI21X2 g156(.A0 (n_17), .A1 (n_15), .B0 (n_16), .Y (n_209));
  OAI21X4 g78(.A0 (n_211), .A1 (n_212), .B0 (n_213), .Y (n_214));
  NAND2X8 g82(.A (in1[0]), .B (in2[0]), .Y (n_211));
  NOR2X8 g79(.A (in1[1]), .B (in2[1]), .Y (n_212));
  NAND2X2 g81(.A (in2[1]), .B (in1[1]), .Y (n_213));
  NAND2X6 g80(.A (in1[1]), .B (in2[1]), .Y (n_215));
  NAND2X1 g9469_dup9505(.A (in2[4]), .B (in1[4]), .Y (n_219));
  NAND2X6 g9506(.A (in2[0]), .B (in1[0]), .Y (n_220));
  NOR2BX1 g2(.AN (n_17), .B (n_42), .Y (n_222));
endmodule


