`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:25:23 CST (Apr 24 2022 03:25:23 UTC)

module DFT_compute_Equal_1U_10_4(in1, out1);
  input [3:0] in1;
  output out1;
  wire [3:0] in1;
  wire out1;
  NOR4X1 g15(.A (in1[2]), .B (in1[1]), .C (in1[3]), .D (in1[0]), .Y
       (out1));
endmodule


