`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:24:50 CST (Apr 24 2022 03:24:50 UTC)

module DFT_compute_LessThanEQ_4Sx3S_1U_1(in2, in1, out1);
  input [3:0] in2;
  input [2:0] in1;
  output out1;
  wire [3:0] in2;
  wire [2:0] in1;
  wire out1;
  wire lte_21_53_n_0, lte_21_53_n_1, lte_21_53_n_2, lte_21_53_n_3,
       lte_21_53_n_4, lte_21_53_n_5, lte_21_53_n_6, lte_21_53_n_7;
  wire lte_21_53_n_8, lte_21_53_n_9, lte_21_53_n_10, lte_21_53_n_11,
       lte_21_53_n_13, lte_21_53_n_14, lte_21_53_n_15, lte_21_53_n_17;
  NOR2X1 lte_21_53_g140(.A (lte_21_53_n_14), .B (lte_21_53_n_15), .Y
       (lte_21_53_n_17));
  NOR2X1 lte_21_53_g142(.A (lte_21_53_n_11), .B (lte_21_53_n_13), .Y
       (lte_21_53_n_15));
  OAI21X2 lte_21_53_g143(.A0 (lte_21_53_n_10), .A1 (lte_21_53_n_8), .B0
       (lte_21_53_n_3), .Y (lte_21_53_n_14));
  AOI21X1 lte_21_53_g144(.A0 (lte_21_53_n_0), .A1 (lte_21_53_n_5), .B0
       (lte_21_53_n_6), .Y (lte_21_53_n_13));
  NAND2X1 lte_21_53_g146(.A (lte_21_53_n_9), .B (lte_21_53_n_7), .Y
       (lte_21_53_n_11));
  NAND2BX1 lte_21_53_g147(.AN (in2[2]), .B (in1[2]), .Y
       (lte_21_53_n_10));
  INVX2 lte_21_53_g149(.A (lte_21_53_n_9), .Y (lte_21_53_n_8));
  NAND2X4 lte_21_53_g150(.A (in2[3]), .B (lte_21_53_n_1), .Y
       (lte_21_53_n_9));
  NAND2X1 lte_21_53_g151(.A (in2[2]), .B (lte_21_53_n_1), .Y
       (lte_21_53_n_7));
  NOR2X1 lte_21_53_g152(.A (lte_21_53_n_2), .B (in2[1]), .Y
       (lte_21_53_n_6));
  NAND2X1 lte_21_53_g153(.A (in2[1]), .B (lte_21_53_n_2), .Y
       (lte_21_53_n_5));
  INVX1 lte_21_53_g154(.A (lte_21_53_n_4), .Y (lte_21_53_n_3));
  NOR2X1 lte_21_53_g155(.A (lte_21_53_n_1), .B (in2[3]), .Y
       (lte_21_53_n_4));
  INVX1 lte_21_53_g157(.A (in1[1]), .Y (lte_21_53_n_2));
  CLKINVX6 lte_21_53_g158(.A (in1[2]), .Y (lte_21_53_n_1));
  NAND2BX1 lte_21_53_g2(.AN (in1[0]), .B (in2[0]), .Y (lte_21_53_n_0));
  OAI21X1 lte_21_53_g161(.A0 (lte_21_53_n_4), .A1 (lte_21_53_n_17), .B0
       (lte_21_53_n_9), .Y (out1));
endmodule


