`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:18:45 CST (Apr 24 2022 03:18:45 UTC)

module DFT_compute_Add_8Ux3U_8U_4(in2, in1, out1);
  input [7:0] in2;
  input [2:0] in1;
  output [7:0] out1;
  wire [7:0] in2;
  wire [2:0] in1;
  wire [7:0] out1;
  wire add_23_2_n_0, add_23_2_n_2, add_23_2_n_5, add_23_2_n_6,
       add_23_2_n_8, add_23_2_n_10, add_23_2_n_12;
  XNOR2X1 add_23_2_g204(.A (in2[7]), .B (add_23_2_n_12), .Y (out1[7]));
  XNOR2X1 add_23_2_g205(.A (in2[6]), .B (add_23_2_n_10), .Y (out1[6]));
  NAND2BX1 add_23_2_g206(.AN (add_23_2_n_10), .B (in2[6]), .Y
       (add_23_2_n_12));
  XNOR2X1 add_23_2_g207(.A (in2[5]), .B (add_23_2_n_8), .Y (out1[5]));
  NAND2BX1 add_23_2_g208(.AN (add_23_2_n_8), .B (in2[5]), .Y
       (add_23_2_n_10));
  XNOR2X1 add_23_2_g209(.A (in2[4]), .B (add_23_2_n_6), .Y (out1[4]));
  NAND2BX1 add_23_2_g210(.AN (add_23_2_n_6), .B (in2[4]), .Y
       (add_23_2_n_8));
  XOR2XL add_23_2_g211(.A (in2[3]), .B (add_23_2_n_5), .Y (out1[3]));
  NAND2X1 add_23_2_g212(.A (in2[3]), .B (add_23_2_n_5), .Y
       (add_23_2_n_6));
  ADDFX1 add_23_2_g213(.A (add_23_2_n_2), .B (in1[2]), .CI (in2[2]),
       .CO (add_23_2_n_5), .S (out1[2]));
  ADDFX1 add_23_2_g214(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_2), .S (out1[1]));
  ADDHX1 add_23_2_g215(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


