`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:24:56 CST (Apr 24 2022 03:24:56 UTC)

module DFT_compute_Add_3Ux3U_3U_1(in2, in1, out1);
  input [2:0] in2, in1;
  output [2:0] out1;
  wire [2:0] in2, in1;
  wire [2:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_8;
  wire add_23_2_n_10, add_23_2_n_12, add_23_2_n_20;
  MXI2XL add_23_2_g40(.A (add_23_2_n_8), .B (add_23_2_n_20), .S0
       (add_23_2_n_12), .Y (out1[2]));
  OAI21X1 add_23_2_g41(.A0 (add_23_2_n_3), .A1 (add_23_2_n_6), .B0
       (add_23_2_n_4), .Y (add_23_2_n_12));
  MXI2XL add_23_2_g42(.A (add_23_2_n_3), .B (add_23_2_n_10), .S0
       (add_23_2_n_1), .Y (out1[1]));
  INVX1 add_23_2_g43(.A (add_23_2_n_3), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g46(.A (add_23_2_n_5), .B (add_23_2_n_0), .Y
       (add_23_2_n_8));
  MXI2XL add_23_2_g47(.A (add_23_2_n_2), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NOR2X1 add_23_2_g48(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g49(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g51(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_4));
  NAND2X2 add_23_2_g53(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_3));
  INVX1 add_23_2_g55(.A (in2[0]), .Y (add_23_2_n_2));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_4), .B (add_23_2_n_6), .Y
       (add_23_2_n_1));
  OR2XL add_23_2_g57(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_0));
  INVXL add_23_2_fopt(.A (add_23_2_n_8), .Y (add_23_2_n_20));
endmodule


