`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:19:01 CST (Apr 24 2022 03:19:01 UTC)

module DFT_compute_Add_3Ux1U_4U_4(in2, in1, out1);
  input [2:0] in2;
  input in1;
  output [3:0] out1;
  wire [2:0] in2;
  wire in1;
  wire [3:0] out1;
  wire inc_add_23_2_n_0, inc_add_23_2_n_2;
  ADDHX1 inc_add_23_2_g26(.A (in2[2]), .B (inc_add_23_2_n_2), .CO
       (out1[3]), .S (out1[2]));
  ADDHX1 inc_add_23_2_g27(.A (in2[1]), .B (inc_add_23_2_n_0), .CO
       (inc_add_23_2_n_2), .S (out1[1]));
  ADDHX1 inc_add_23_2_g28(.A (in2[0]), .B (in1), .CO
       (inc_add_23_2_n_0), .S (out1[0]));
endmodule


