`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:16:49 CST (Apr 24 2022 06:16:49 UTC)

module DFT_compute_Add_2Ux1U_3U_0(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [2:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [2:0] out1;
  wire n_0, n_3, n_12, n_13, n_14, n_15, n_16;
  NOR2BX1 g164(.AN (in2[0]), .B (n_3), .Y (out1[2]));
  NAND2X2 g166(.A (in2[1]), .B (in1), .Y (n_3));
  INVX1 g168(.A (in2[1]), .Y (n_0));
  OAI21X2 g64(.A0 (n_0), .A1 (n_14), .B0 (n_16), .Y (out1[1]));
  NOR2X4 g66(.A (n_12), .B (n_13), .Y (n_14));
  CLKINVX6 g68(.A (in2[0]), .Y (n_12));
  INVX2 g67(.A (in1), .Y (n_13));
  NAND3X8 g65(.A (in1), .B (in2[0]), .C (n_15), .Y (n_16));
  INVX8 g69(.A (in2[1]), .Y (n_15));
  MXI2X1 g18(.A (n_12), .B (in2[0]), .S0 (in1), .Y (out1[0]));
endmodule


