`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:13:31 CST (Apr 24 2022 07:13:31 UTC)

module DFT_compute_entirecomputation_alt4_4_0(in1, in2, out1);
  input [7:0] in1;
  input [31:0] in2;
  output [39:0] out1;
  wire [7:0] in1;
  wire [31:0] in2;
  wire [39:0] out1;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  assign out1[3] = in1[3];
  assign out1[4] = in1[4];
  assign out1[5] = in1[5];
  assign out1[6] = in1[6];
  assign out1[7] = in1[7];
  assign out1[8] = in2[0];
  assign out1[9] = in2[1];
  assign out1[10] = in2[2];
  assign out1[11] = in2[3];
  assign out1[12] = in2[4];
  assign out1[13] = in2[5];
  assign out1[14] = in2[6];
  assign out1[15] = in2[7];
  assign out1[16] = in2[8];
  assign out1[17] = in2[9];
  assign out1[18] = in2[10];
  assign out1[19] = in2[11];
  assign out1[20] = in2[12];
  assign out1[21] = in2[13];
  assign out1[22] = in2[14];
  assign out1[23] = in2[15];
  assign out1[24] = in2[16];
  assign out1[25] = in2[17];
  assign out1[26] = in2[18];
  assign out1[27] = in2[19];
  assign out1[28] = in2[20];
  assign out1[29] = in2[21];
  assign out1[30] = in2[22];
  assign out1[31] = in2[23];
  assign out1[32] = in2[24];
  assign out1[33] = in2[25];
  assign out1[34] = in2[26];
  assign out1[35] = in2[27];
  assign out1[36] = in2[28];
  assign out1[37] = in2[29];
  assign out1[38] = in2[30];
  assign out1[39] = in2[31];
endmodule


