`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:13:35 CST (Apr 24 2022 07:13:35 UTC)

module DFT_compute_entirecomputation_4_0(in1, out1);
  input [1:0] in1;
  output [47:0] out1;
  wire [1:0] in1;
  wire [47:0] out1;
  wire asc088_1_, asc088_2_, n_0, n_1, n_2, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_15, sll_426_30_n_1, sll_426_30_n_2;
  assign out1[0] = 1'b0;
  assign out1[1] = 1'b0;
  assign out1[2] = 1'b0;
  assign out1[3] = 1'b0;
  assign out1[4] = 1'b0;
  assign out1[5] = 1'b0;
  assign out1[6] = 1'b0;
  assign out1[7] = 1'b0;
  assign out1[8] = 1'b0;
  assign out1[9] = 1'b0;
  assign out1[10] = 1'b0;
  assign out1[11] = 1'b0;
  assign out1[12] = 1'b0;
  assign out1[13] = 1'b0;
  assign out1[14] = 1'b0;
  assign out1[15] = 1'b0;
  assign out1[16] = 1'b0;
  assign out1[17] = 1'b0;
  assign out1[18] = 1'b0;
  assign out1[19] = 1'b0;
  assign out1[25] = out1[29];
  assign out1[26] = out1[29];
  assign out1[27] = out1[29];
  assign out1[28] = out1[29];
  assign out1[31] = 1'b0;
  assign out1[32] = out1[41];
  assign out1[33] = out1[42];
  assign out1[34] = out1[43];
  assign out1[35] = 1'b0;
  assign out1[36] = 1'b0;
  assign out1[37] = 1'b0;
  assign out1[38] = 1'b0;
  assign out1[39] = 1'b0;
  assign out1[44] = 1'b0;
  assign out1[45] = 1'b0;
  assign out1[46] = 1'b0;
  assign out1[47] = 1'b0;
  INVX1 g949(.A (out1[40]), .Y (n_2));
  AND2XL g961(.A (n_7), .B (n_10), .Y (out1[22]));
  AND2XL g962(.A (n_6), .B (n_10), .Y (out1[21]));
  AND2XL g963(.A (n_5), .B (n_10), .Y (out1[20]));
  OAI21X1 g954(.A0 (in1[0]), .A1 (out1[40]), .B0 (n_1), .Y (n_15));
  NOR2X1 g955(.A (in1[1]), .B (in1[0]), .Y (out1[40]));
  INVX1 g956(.A (in1[1]), .Y (n_1));
  INVX2 g957(.A (in1[0]), .Y (n_12));
  AND2X1 g999(.A (n_9), .B (n_10), .Y (out1[30]));
  AND2XL g1000(.A (n_12), .B (n_10), .Y (out1[23]));
  NOR2BX1 g1001(.AN (n_10), .B (n_9), .Y (out1[29]));
  AND2XL g1002(.A (n_8), .B (n_10), .Y (out1[24]));
  OR4X1 g1003(.A (n_0), .B (out1[42]), .C (out1[43]), .D (out1[41]), .Y
       (n_10));
  NOR2BX1 g1004(.AN (out1[42]), .B (n_11), .Y (asc088_2_));
  OA21X1 g1005(.A0 (in1[0]), .A1 (n_15), .B0 (out1[41]), .Y
       (asc088_1_));
  NOR2BX1 g1006(.AN (in1[1]), .B (in1[0]), .Y (out1[42]));
  NOR2BX1 g1007(.AN (in1[1]), .B (n_12), .Y (out1[43]));
  NOR2X1 g1008(.A (in1[1]), .B (n_12), .Y (out1[41]));
  INVX1 g1009(.A (n_2), .Y (n_0));
  INVX1 g1010(.A (n_15), .Y (n_11));
  MX3XL sll_426_30_g284(.A (asc088_2_), .B (asc088_1_), .C
       (sll_426_30_n_1), .S0 (n_12), .S1 (n_11), .Y (n_7));
  NOR2XL sll_426_30_g285(.A (n_11), .B (sll_426_30_n_2), .Y (n_6));
  NOR2BX1 sll_426_30_g286(.AN (sll_426_30_n_1), .B (n_11), .Y (n_5));
  MXI2XL sll_426_30_g287(.A (asc088_1_), .B (out1[40]), .S0 (n_12), .Y
       (sll_426_30_n_2));
  NOR2BX1 sll_426_30_g288(.AN (out1[40]), .B (n_12), .Y
       (sll_426_30_n_1));
  OAI2BB1X1 addinc_add_491_2_g67(.A0N (n_15), .A1N (in1[0]), .B0 (n_9),
       .Y (n_8));
  OR2X1 addinc_add_491_2_g68(.A (n_15), .B (in1[0]), .Y (n_9));
endmodule


