`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:13:30 CST (Apr 24 2022 07:13:30 UTC)

module DFT_compute_entirecomputation_alt5_4_0(in1, in2, out1);
  input [7:0] in1, in2;
  output [7:0] out1;
  wire [7:0] in1, in2;
  wire [7:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_3, add_23_2_n_5,
       add_23_2_n_7, add_23_2_n_9, add_23_2_n_11, add_23_2_n_13;
  XNOR2X1 add_23_2_g245(.A (add_23_2_n_0), .B (add_23_2_n_13), .Y
       (out1[7]));
  ADDFX1 add_23_2_g246(.A (add_23_2_n_11), .B (in2[6]), .CI (in1[6]),
       .CO (add_23_2_n_13), .S (out1[6]));
  ADDFX1 add_23_2_g247(.A (add_23_2_n_9), .B (in2[5]), .CI (in1[5]),
       .CO (add_23_2_n_11), .S (out1[5]));
  ADDFX1 add_23_2_g248(.A (add_23_2_n_7), .B (in2[4]), .CI (in1[4]),
       .CO (add_23_2_n_9), .S (out1[4]));
  ADDFX1 add_23_2_g249(.A (add_23_2_n_5), .B (in2[3]), .CI (in1[3]),
       .CO (add_23_2_n_7), .S (out1[3]));
  ADDFX1 add_23_2_g250(.A (add_23_2_n_3), .B (in2[2]), .CI (in1[2]),
       .CO (add_23_2_n_5), .S (out1[2]));
  ADDFX1 add_23_2_g251(.A (add_23_2_n_1), .B (in2[1]), .CI (in1[1]),
       .CO (add_23_2_n_3), .S (out1[1]));
  ADDHX1 add_23_2_g252(.A (in1[0]), .B (in2[0]), .CO (add_23_2_n_1), .S
       (out1[0]));
  XNOR2X1 add_23_2_g253(.A (in1[7]), .B (in2[7]), .Y (add_23_2_n_0));
endmodule


