`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:28:46 CST (Apr 24 2022 07:28:46 UTC)

module DFT_compute_LessThan_2Ux8U_1U_1(in2, in1, out1);
  input [1:0] in2;
  input [7:0] in1;
  output out1;
  wire [1:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5, gt_21_21_n_6, gt_21_21_n_7;
  wire gt_21_21_n_8, gt_21_21_n_9;
  NAND2X1 gt_21_21_g115(.A (gt_21_21_n_8), .B (gt_21_21_n_9), .Y
       (out1));
  NOR2X1 gt_21_21_g116(.A (gt_21_21_n_0), .B (gt_21_21_n_7), .Y
       (gt_21_21_n_9));
  OAI21X1 gt_21_21_g117(.A0 (gt_21_21_n_1), .A1 (gt_21_21_n_3), .B0
       (gt_21_21_n_4), .Y (gt_21_21_n_8));
  NAND2X1 gt_21_21_g118(.A (gt_21_21_n_6), .B (gt_21_21_n_5), .Y
       (gt_21_21_n_7));
  NOR2X4 gt_21_21_g120(.A (in1[5]), .B (in1[4]), .Y (gt_21_21_n_6));
  NOR2X2 gt_21_21_g121(.A (in1[3]), .B (in1[2]), .Y (gt_21_21_n_5));
  NAND2X1 gt_21_21_g122(.A (in2[1]), .B (gt_21_21_n_2), .Y
       (gt_21_21_n_4));
  NOR2X1 gt_21_21_g124(.A (gt_21_21_n_2), .B (in2[1]), .Y
       (gt_21_21_n_3));
  INVX1 gt_21_21_g126(.A (in1[1]), .Y (gt_21_21_n_2));
  NOR2BX1 gt_21_21_g2(.AN (in1[0]), .B (in2[0]), .Y (gt_21_21_n_1));
  OR2XL gt_21_21_g129(.A (in1[7]), .B (in1[6]), .Y (gt_21_21_n_0));
endmodule


