`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:17:12 CST (Apr 24 2022 06:17:12 UTC)

module DFT_compute_Add_8Ux1U_8U_0(in2, in1, out1);
  input [7:0] in2;
  input in1;
  output [7:0] out1;
  wire [7:0] in2;
  wire in1;
  wire [7:0] out1;
  wire n_1, n_5, n_9, n_12, n_13, n_14, n_15, n_16;
  wire n_19, n_22, n_50, n_55, n_56, n_58, n_78, n_88;
  wire n_89, n_91, n_93, n_96, n_97, n_98, n_100, n_101;
  wire n_103, n_104, n_105, n_106, n_111, n_112;
  MXI2XL g2123(.A (n_22), .B (in2[3]), .S0 (n_13), .Y (out1[3]));
  MXI2XL g2116(.A (n_1), .B (in2[2]), .S0 (n_16), .Y (out1[2]));
  MXI2XL g2119(.A (in2[1]), .B (n_15), .S0 (n_14), .Y (out1[1]));
  NOR2X1 g2122(.A (n_15), .B (n_14), .Y (n_16));
  NOR2X1 g2129(.A (n_12), .B (n_19), .Y (n_13));
  MXI2X1 g2132(.A (n_5), .B (in1), .S0 (in2[0]), .Y (out1[0]));
  NAND2X2 g2137(.A (in2[0]), .B (in1), .Y (n_14));
  NAND2X8 g2136(.A (in2[3]), .B (in1), .Y (n_9));
  NAND2X4 g2135(.A (in2[2]), .B (in1), .Y (n_12));
  NAND2X8 g2139(.A (in2[0]), .B (in2[1]), .Y (n_19));
  INVX1 g2143(.A (in1), .Y (n_5));
  INVX1 g2141(.A (in2[2]), .Y (n_1));
  INVX1 g2142(.A (in2[1]), .Y (n_15));
  NAND2X4 g259(.A (in2[4]), .B (in2[2]), .Y (n_50));
  NAND2X8 g25(.A (in2[5]), .B (in2[6]), .Y (n_55));
  NAND2X8 g27(.A (in2[2]), .B (in2[4]), .Y (n_56));
  NAND2X1 g26(.A (in2[2]), .B (in2[4]), .Y (n_58));
  NOR3X2 g502(.A (in2[7]), .B (n_9), .C (n_19), .Y (n_78));
  INVX2 g37(.A (in2[3]), .Y (n_22));
  MXI2XL g88(.A (n_88), .B (in2[4]), .S0 (n_89), .Y (out1[4]));
  INVX1 g90(.A (in2[4]), .Y (n_88));
  NOR3X2 g89(.A (n_22), .B (n_12), .C (n_19), .Y (n_89));
  NAND2X4 g17(.A (in2[0]), .B (in2[5]), .Y (n_91));
  NAND2X6 g2158(.A (in2[1]), .B (in1), .Y (n_93));
  OAI2BB1X1 g2159(.A0N (in2[6]), .A1N (n_98), .B0 (n_101), .Y
       (out1[6]));
  NAND2X1 g2160(.A (n_96), .B (n_97), .Y (n_98));
  NOR2X2 g507(.A (n_22), .B (n_91), .Y (n_96));
  NOR2X4 g506(.A (n_93), .B (n_50), .Y (n_97));
  NAND2X1 g2161(.A (n_97), .B (n_100), .Y (n_101));
  NOR3X2 g2162(.A (n_22), .B (n_91), .C (in2[6]), .Y (n_100));
  OAI2BB1X1 g126(.A0N (in2[7]), .A1N (n_105), .B0 (n_106), .Y
       (out1[7]));
  NAND2X1 g128(.A (n_103), .B (n_104), .Y (n_105));
  NOR2X4 g129(.A (n_55), .B (n_56), .Y (n_103));
  NOR2X2 g130(.A (n_9), .B (n_19), .Y (n_104));
  NAND2X1 g127(.A (n_103), .B (n_78), .Y (n_106));
  MXI2XL g2164(.A (n_111), .B (in2[5]), .S0 (n_112), .Y (out1[5]));
  INVXL g2165(.A (in2[5]), .Y (n_111));
  NOR3X2 g2166(.A (n_9), .B (n_19), .C (n_58), .Y (n_112));
endmodule


