`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 12:09:52 CST (Apr 24 2022 04:09:52 UTC)

module DFT_compute_LessThan_3Ux8U_1U_4(in2, in1, out1);
  input [2:0] in2;
  input [7:0] in1;
  output out1;
  wire [2:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5, gt_21_21_n_6, gt_21_21_n_7;
  OR4X1 gt_21_21_g145(.A (gt_21_21_n_3), .B (in1[4]), .C (in1[7]), .D
       (gt_21_21_n_7), .Y (out1));
  AOI32X1 gt_21_21_g146(.A0 (gt_21_21_n_4), .A1 (gt_21_21_n_0), .A2
       (gt_21_21_n_6), .B0 (in2[2]), .B1 (gt_21_21_n_1), .Y
       (gt_21_21_n_7));
  OAI21X1 gt_21_21_g147(.A0 (in1[1]), .A1 (gt_21_21_n_2), .B0
       (gt_21_21_n_5), .Y (gt_21_21_n_6));
  OAI2BB1X1 gt_21_21_g148(.A0N (in1[1]), .A1N (gt_21_21_n_2), .B0
       (in2[1]), .Y (gt_21_21_n_5));
  NAND2BXL gt_21_21_g149(.AN (in2[2]), .B (in1[2]), .Y (gt_21_21_n_4));
  OR2XL gt_21_21_g150(.A (in1[6]), .B (in1[5]), .Y (gt_21_21_n_3));
  NOR2BX1 gt_21_21_g151(.AN (in1[0]), .B (in2[0]), .Y (gt_21_21_n_2));
  NOR2X1 gt_21_21_g152(.A (in1[3]), .B (in1[2]), .Y (gt_21_21_n_1));
  INVX1 gt_21_21_g153(.A (in1[3]), .Y (gt_21_21_n_0));
endmodule


