`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:19:33 CST (Apr 24 2022 06:19:33 UTC)

module DFT_compute_Add_3Ux1U_4U_0(in2, in1, out1);
  input [2:0] in2;
  input in1;
  output [3:0] out1;
  wire [2:0] in2;
  wire in1;
  wire [3:0] out1;
  wire n_3, n_71, n_85, n_91, n_92, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103;
  MXI2X1 g211(.A (n_85), .B (in2[0]), .S0 (in1), .Y (out1[0]));
  NAND2X1 g212(.A (in2[2]), .B (in2[1]), .Y (n_3));
  MXI2X1 g60(.A (in2[1]), .B (n_91), .S0 (n_71), .Y (out1[1]));
  NAND2X4 g62(.A (in1), .B (in2[0]), .Y (n_71));
  NOR2X1 g61(.A (n_71), .B (n_3), .Y (out1[3]));
  CLKINVX6 g12_dup(.A (in2[0]), .Y (n_85));
  CLKINVX8 g13(.A (in2[1]), .Y (n_91));
  INVX3 g14(.A (in1), .Y (n_92));
  OAI21X2 g132(.A0 (n_97), .A1 (n_100), .B0 (n_103), .Y (out1[2]));
  INVX1 g139(.A (in2[2]), .Y (n_97));
  NOR2X4 g133(.A (n_98), .B (n_99), .Y (n_100));
  INVX2 g138(.A (in2[0]), .Y (n_98));
  NAND2X8 g136(.A (in2[1]), .B (in1), .Y (n_99));
  NAND2X2 g134(.A (n_101), .B (n_102), .Y (n_103));
  NOR2X4 g232(.A (in2[2]), .B (n_85), .Y (n_101));
  NOR2X4 g233(.A (n_91), .B (n_92), .Y (n_102));
endmodule


