`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:14:21 CST (Apr 24 2022 07:14:21 UTC)

module DFT_compute_Add_2Ux1U_2U_0(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output [1:0] out1;
  wire [1:0] in2;
  wire in1;
  wire [1:0] out1;
  wire n_13, n_23, n_26, n_29, n_30, n_31, n_33;
  MXI2X1 g113(.A (n_13), .B (in2[0]), .S0 (in1), .Y (out1[0]));
  CLKINVX4 g114(.A (in2[0]), .Y (n_13));
  CLKINVX8 g74(.A (in2[1]), .Y (n_23));
  INVX1 g16(.A (in2[1]), .Y (n_26));
  OAI21X2 g33(.A0 (n_26), .A1 (n_31), .B0 (n_33), .Y (out1[1]));
  NOR2X4 g34(.A (n_29), .B (n_30), .Y (n_31));
  CLKINVX4 g36(.A (in1), .Y (n_29));
  INVX2 g35(.A (in2[0]), .Y (n_30));
  NAND3X8 g118(.A (in2[0]), .B (in1), .C (n_23), .Y (n_33));
endmodule


