`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:17:36 CST (Apr 24 2022 06:17:36 UTC)

module DFT_compute_Add_3Ux3U_4U_0(in2, in1, out1);
  input [2:0] in2, in1;
  output [3:0] out1;
  wire [2:0] in2, in1;
  wire [3:0] out1;
  wire n_2, n_14, n_60, n_68, n_71, n_98, n_106, n_117;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_132, n_133;
  INVX2 g735(.A (n_132), .Y (n_14));
  MXI2X1 g737(.A (n_2), .B (in2[0]), .S0 (in1[0]), .Y (out1[0]));
  INVX1 g747(.A (in2[0]), .Y (n_2));
  MXI2X1 g229(.A (n_14), .B (n_132), .S0 (n_125), .Y (out1[2]));
  AOI2BB1XL g44(.A0N (n_127), .A1N (n_71), .B0 (n_98), .Y (n_60));
  MXI2X1 g48(.A (n_128), .B (n_68), .S0 (n_129), .Y (out1[1]));
  INVXL g50(.A (n_128), .Y (n_68));
  NOR2X8 g144(.A (in1[2]), .B (in2[2]), .Y (n_71));
  NOR2BX1 g2(.AN (in2[2]), .B (n_133), .Y (n_98));
  NAND2X1 g18(.A (n_106), .B (n_60), .Y (out1[3]));
  NAND2BX1 g19(.AN (n_128), .B (n_117), .Y (n_106));
  NOR2X1 g775(.A (n_126), .B (n_71), .Y (n_117));
  OAI21X4 g78(.A0 (n_122), .A1 (n_123), .B0 (n_124), .Y (n_125));
  NAND2X8 g82(.A (in2[0]), .B (in1[0]), .Y (n_122));
  NOR2X6 g79_dup(.A (in1[1]), .B (in2[1]), .Y (n_123));
  NAND2X2 g81(.A (in2[1]), .B (in1[1]), .Y (n_124));
  NOR2X2 g79(.A (in1[1]), .B (in2[1]), .Y (n_126));
  NAND2X1 g80(.A (in2[1]), .B (in1[1]), .Y (n_127));
  NAND2X2 g776(.A (in1[0]), .B (in2[0]), .Y (n_128));
  AOI21X1 g777(.A0 (in2[1]), .A1 (in1[1]), .B0 (n_126), .Y (n_129));
  AOI21X4 g778(.A0 (in2[2]), .A1 (in1[2]), .B0 (n_71), .Y (n_132));
  CLKINVX8 g779(.A (in1[2]), .Y (n_133));
endmodule


