`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:16:29 CST (Apr 24 2022 07:16:29 UTC)

module DFT_compute_Equal_1U_10_4_0(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR4X1 g30(.A (in1[5]), .B (in1[4]), .C (n_0), .D (n_1), .Y (out1));
  OR4X1 g31(.A (in1[0]), .B (in1[1]), .C (in1[3]), .D (in1[2]), .Y
       (n_1));
  OR2XL g32(.A (in1[7]), .B (in1[6]), .Y (n_0));
endmodule


