`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 16:17:32 CST (Apr 24 2022 08:17:32 UTC)

module DFT_compute_LessThanEQ_1U_15_1(in1, out1);
  input [3:0] in1;
  output out1;
  wire [3:0] in1;
  wire out1;
  NAND2BX1 lte_19_53_g2(.AN (in1[3]), .B (in1[2]), .Y (out1));
endmodule


