`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 12:09:55 CST (Apr 24 2022 04:09:55 UTC)

module DFT_compute_LessThan_3Ux8U_1U_1(in2, in1, out1);
  input [2:0] in2;
  input [7:0] in1;
  output out1;
  wire [2:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5, gt_21_21_n_6, gt_21_21_n_7;
  wire gt_21_21_n_8, gt_21_21_n_9, gt_21_21_n_10, gt_21_21_n_11;
  OAI21X1 gt_21_21_g115(.A0 (gt_21_21_n_8), .A1 (gt_21_21_n_11), .B0
       (gt_21_21_n_6), .Y (out1));
  NOR2BX1 gt_21_21_g116(.AN (gt_21_21_n_9), .B (gt_21_21_n_10), .Y
       (gt_21_21_n_11));
  NOR2X1 gt_21_21_g117(.A (gt_21_21_n_0), .B (gt_21_21_n_7), .Y
       (gt_21_21_n_10));
  AOI21X1 gt_21_21_g118(.A0 (in1[2]), .A1 (gt_21_21_n_3), .B0 (in1[3]),
       .Y (gt_21_21_n_9));
  NOR3X1 gt_21_21_g119(.A (in1[3]), .B (gt_21_21_n_3), .C (in1[2]), .Y
       (gt_21_21_n_8));
  NOR2X1 gt_21_21_g120(.A (gt_21_21_n_1), .B (gt_21_21_n_2), .Y
       (gt_21_21_n_7));
  AND2XL gt_21_21_g121(.A (gt_21_21_n_4), .B (gt_21_21_n_5), .Y
       (gt_21_21_n_6));
  NOR2X1 gt_21_21_g124(.A (in1[5]), .B (in1[4]), .Y (gt_21_21_n_5));
  NOR2X1 gt_21_21_g126(.A (in1[7]), .B (in1[6]), .Y (gt_21_21_n_4));
  INVX1 gt_21_21_g129(.A (in2[2]), .Y (gt_21_21_n_3));
  NOR2BX1 gt_21_21_g2(.AN (in1[0]), .B (in2[0]), .Y (gt_21_21_n_2));
  NOR2BX1 gt_21_21_g131(.AN (in1[1]), .B (in2[1]), .Y (gt_21_21_n_1));
  NOR2BX1 gt_21_21_g132(.AN (in2[1]), .B (in1[1]), .Y (gt_21_21_n_0));
endmodule


