`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:14:14 CST (Apr 24 2022 07:14:14 UTC)

module DFT_compute_LessThan_3Ux8U_1U_0(in2, in1, out1);
  input [2:0] in2;
  input [7:0] in1;
  output out1;
  wire [2:0] in2;
  wire [7:0] in1;
  wire out1;
  wire n_128, n_129, n_141, n_142, n_143, n_144, n_145, n_147;
  wire n_148, n_151, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_183, n_184;
  NAND2X6 g929(.A (in1[2]), .B (n_128), .Y (n_129));
  CLKINVX4 g930(.A (in2[2]), .Y (n_128));
  NAND2X2 g341(.A (n_148), .B (n_151), .Y (out1));
  NOR2X4 g931(.A (n_143), .B (n_147), .Y (n_148));
  NAND2X6 g932(.A (n_141), .B (n_142), .Y (n_143));
  INVX2 g933(.A (in1[3]), .Y (n_141));
  NOR2X8 g934(.A (in1[5]), .B (in1[4]), .Y (n_142));
  NOR3X4 g935(.A (n_144), .B (n_145), .C (in2[1]), .Y (n_147));
  INVX2 g936(.A (in1[1]), .Y (n_144));
  NOR2X4 g937(.A (in1[2]), .B (n_160), .Y (n_145));
  NOR2X4 g939(.A (n_184), .B (n_159), .Y (n_151));
  NOR3X4 g130(.A (n_154), .B (n_156), .C (n_158), .Y (n_159));
  NOR2X6 g132(.A (in1[1]), .B (n_153), .Y (n_154));
  CLKINVX8 g136(.A (in2[1]), .Y (n_153));
  NOR2X4 g133(.A (in1[2]), .B (n_155), .Y (n_156));
  INVX3 g134(.A (in2[2]), .Y (n_155));
  NAND2X6 g131(.A (in1[0]), .B (n_157), .Y (n_158));
  CLKINVX4 g137(.A (in2[0]), .Y (n_157));
  CLKINVX6 g135(.A (in2[2]), .Y (n_160));
  NAND2X6 g13(.A (n_183), .B (n_129), .Y (n_184));
  NOR2X8 g14(.A (in1[6]), .B (in1[7]), .Y (n_183));
endmodule


