`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 12:12:57 CST (Apr 24 2022 04:12:57 UTC)

module DFT_compute_Add_3Ux2U_3U_1(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [2:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [2:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_9, add_23_2_n_19;
  wire add_23_2_n_20;
  MXI2XL add_23_2_g41(.A (add_23_2_n_1), .B (in2[2]), .S0
       (add_23_2_n_9), .Y (out1[2]));
  OAI21X2 add_23_2_g42(.A0 (add_23_2_n_3), .A1 (add_23_2_n_4), .B0
       (add_23_2_n_5), .Y (add_23_2_n_9));
  MXI2X1 add_23_2_g43(.A (add_23_2_n_19), .B (add_23_2_n_20), .S0
       (add_23_2_n_0), .Y (out1[1]));
  MXI2XL add_23_2_g46(.A (add_23_2_n_2), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NAND2X8 add_23_2_g48(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_5));
  NOR2X4 add_23_2_g49(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_4));
  NAND2X8 add_23_2_g50(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_3));
  INVX1 add_23_2_g51(.A (in2[0]), .Y (add_23_2_n_2));
  INVXL add_23_2_g52(.A (in2[2]), .Y (add_23_2_n_1));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_5), .B (add_23_2_n_4), .Y
       (add_23_2_n_0));
  CLKINVX1 add_23_2_fopt(.A (add_23_2_n_20), .Y (add_23_2_n_19));
  CLKINVX1 add_23_2_fopt54(.A (add_23_2_n_3), .Y (add_23_2_n_20));
endmodule


