`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:14:17 CST (Apr 24 2022 07:14:17 UTC)

module DFT_compute_LessThan_2Ux2U_1U_0(in2, in1, out1);
  input [1:0] in2, in1;
  output out1;
  wire [1:0] in2, in1;
  wire out1;
  wire n_10, n_12, n_20, n_21, n_22;
  CLKINVX8 g196(.A (in2[1]), .Y (n_10));
  CLKINVX12 g193_dup(.A (in2[1]), .Y (n_12));
  OAI31X4 g95(.A0 (in2[0]), .A1 (n_20), .A2 (n_21), .B0 (n_22), .Y
       (out1));
  INVX3 g98(.A (in1[0]), .Y (n_20));
  NOR2X6 g96(.A (in1[1]), .B (n_10), .Y (n_21));
  NAND2X6 g97(.A (in1[1]), .B (n_12), .Y (n_22));
endmodule


