`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 16:17:25 CST (Apr 24 2022 08:17:25 UTC)

module DFT_compute_Add_2U_6_4(in1, out1);
  input [1:0] in1;
  output [1:0] out1;
  wire [1:0] in1;
  wire [1:0] out1;
  INVX1 g4(.A (in1[0]), .Y (out1[0]));
  XOR2XL inc_add_21_2_g11(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
endmodule


