`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 16:17:28 CST (Apr 24 2022 08:17:28 UTC)

module DFT_compute_LeftShift_5S_16_4(in1, out1);
  input [1:0] in1;
  output [4:0] out1;
  wire [1:0] in1;
  wire [4:0] out1;
  assign out1[4] = 1'b0;
  AND2XL g30(.A (in1[1]), .B (in1[0]), .Y (out1[3]));
  NOR2X1 g31(.A (in1[1]), .B (in1[0]), .Y (out1[0]));
  NOR2BX1 g32(.AN (in1[1]), .B (in1[0]), .Y (out1[2]));
  NOR2BX1 g33(.AN (in1[0]), .B (in1[1]), .Y (out1[1]));
endmodule


