`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:29:03 CST (Apr 24 2022 07:29:03 UTC)

module DFT_compute_Equal_1U_11_4_0(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0;
  NOR3BX1 g16(.AN (n_0), .B (in1[3]), .C (in1[2]), .Y (out1));
  NOR4X1 g17(.A (in1[5]), .B (in1[4]), .C (in1[1]), .D (in1[0]), .Y
       (n_0));
endmodule


