`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:24:55 CST (Apr 24 2022 03:24:55 UTC)

module DFT_compute_Not_1U_1U_1(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  CLKINVX12 g2(.A (in1), .Y (out1));
endmodule


