`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:13:40 CST (Apr 24 2022 07:13:40 UTC)

module DFT_compute_entirecomputation_1(in1, out1);
  input [1:0] in1;
  output [47:0] out1;
  wire [1:0] in1;
  wire [47:0] out1;
  wire addinc_add_491_2_n_1, asc088_1_, asc088_2_, n_0, n_2, n_3, n_4,
       n_5;
  wire n_6, n_7, n_8, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_21, n_30, n_31, n_33, n_34, n_35;
  wire n_36, n_38, sll_426_30_n_1, sll_426_30_n_2, sll_426_30_n_3,
       sll_426_30_n_4, sll_426_30_n_5, sll_426_30_n_6;
  wire sll_426_30_n_7, sll_426_30_n_9, sll_426_30_n_10;
  assign out1[0] = 1'b0;
  assign out1[1] = 1'b0;
  assign out1[2] = 1'b0;
  assign out1[3] = 1'b0;
  assign out1[4] = 1'b0;
  assign out1[5] = 1'b0;
  assign out1[6] = 1'b0;
  assign out1[7] = 1'b0;
  assign out1[8] = 1'b0;
  assign out1[9] = 1'b0;
  assign out1[10] = 1'b0;
  assign out1[11] = 1'b0;
  assign out1[12] = 1'b0;
  assign out1[13] = 1'b0;
  assign out1[14] = 1'b0;
  assign out1[15] = 1'b0;
  assign out1[16] = 1'b0;
  assign out1[17] = 1'b0;
  assign out1[18] = 1'b0;
  assign out1[19] = 1'b0;
  assign out1[25] = out1[29];
  assign out1[26] = out1[29];
  assign out1[27] = out1[29];
  assign out1[28] = out1[29];
  assign out1[31] = 1'b0;
  assign out1[32] = out1[41];
  assign out1[33] = out1[42];
  assign out1[34] = out1[43];
  assign out1[35] = 1'b0;
  assign out1[36] = 1'b0;
  assign out1[37] = 1'b0;
  assign out1[38] = 1'b0;
  assign out1[39] = 1'b0;
  assign out1[44] = 1'b0;
  assign out1[45] = 1'b0;
  assign out1[46] = 1'b0;
  assign out1[47] = 1'b0;
  INVX1 g950(.A (out1[40]), .Y (n_8));
  AND2X1 g961(.A (n_13), .B (n_16), .Y (out1[22]));
  NOR2BX1 g962(.AN (n_16), .B (n_7), .Y (out1[21]));
  NOR2BX1 g963(.AN (n_16), .B (n_6), .Y (out1[20]));
  INVX1 g964(.A (n_12), .Y (n_7));
  INVX1 g965(.A (n_11), .Y (n_6));
  OAI21X4 g954(.A0 (in1[0]), .A1 (out1[40]), .B0 (n_5), .Y (n_21));
  NOR2X6 g955(.A (in1[1]), .B (in1[0]), .Y (out1[40]));
  INVX1 g956(.A (in1[1]), .Y (n_5));
  INVX2 g957(.A (in1[0]), .Y (n_18));
  AND2XL g999(.A (n_15), .B (n_16), .Y (out1[30]));
  NOR2BX1 g1000(.AN (n_18), .B (n_4), .Y (out1[23]));
  NOR2X2 g1001(.A (n_15), .B (n_4), .Y (out1[29]));
  NOR2BX1 g1002(.AN (n_14), .B (n_4), .Y (out1[24]));
  INVX1 g1003(.A (n_4), .Y (n_16));
  NOR2X4 g1004(.A (n_3), .B (n_2), .Y (n_4));
  NOR2BX1 g1005(.AN (n_31), .B (n_36), .Y (asc088_2_));
  NAND2X1 g1006(.A (n_8), .B (n_30), .Y (n_3));
  OR2X1 g1007(.A (out1[43]), .B (n_33), .Y (n_2));
  AOI2BB1XL g1008(.A0N (in1[0]), .A1N (n_21), .B0 (n_34), .Y
       (asc088_1_));
  NOR2X2 g1013(.A (in1[1]), .B (n_18), .Y (n_33));
  NAND2BX4 g2(.AN (in1[0]), .B (in1[1]), .Y (n_0));
  NOR2BX2 g1017(.AN (in1[1]), .B (n_18), .Y (out1[43]));
  CLKINVX1 fopt(.A (n_30), .Y (out1[42]));
  CLKINVX1 fopt1022(.A (n_31), .Y (n_30));
  CLKINVX2 fopt1023(.A (n_0), .Y (n_31));
  BUFX3 fopt1024(.A (n_33), .Y (out1[41]));
  CLKINVX1 fopt1025(.A (n_33), .Y (n_34));
  CLKINVX1 fopt1026(.A (n_36), .Y (n_35));
  CLKINVX1 fopt1027(.A (n_21), .Y (n_36));
  CLKINVX4 fopt1028(.A (n_21), .Y (n_38));
  MXI2XL addinc_add_491_2_g92(.A (in1[0]), .B (addinc_add_491_2_n_1),
       .S0 (n_35), .Y (n_14));
  NAND2BX1 addinc_add_491_2_g93(.AN (n_35), .B (addinc_add_491_2_n_1),
       .Y (n_15));
  INVX1 addinc_add_491_2_g94(.A (in1[0]), .Y (addinc_add_491_2_n_1));
  NAND3X1 sll_426_30_g368(.A (sll_426_30_n_5), .B (sll_426_30_n_7), .C
       (sll_426_30_n_10), .Y (n_13));
  NAND2X1 sll_426_30_g369(.A (sll_426_30_n_6), .B (sll_426_30_n_9), .Y
       (n_12));
  NAND2XL sll_426_30_g370(.A (sll_426_30_n_4), .B (asc088_1_), .Y
       (sll_426_30_n_10));
  NAND2XL sll_426_30_g371(.A (sll_426_30_n_3), .B (asc088_1_), .Y
       (sll_426_30_n_9));
  NOR3BX1 sll_426_30_g372(.AN (sll_426_30_n_2), .B (sll_426_30_n_1), .C
       (n_38), .Y (n_11));
  NAND2X1 sll_426_30_g373(.A (sll_426_30_n_3), .B (asc088_2_), .Y
       (sll_426_30_n_7));
  NAND2X1 sll_426_30_g374(.A (out1[40]), .B (sll_426_30_n_4), .Y
       (sll_426_30_n_6));
  NAND3X1 sll_426_30_g375(.A (sll_426_30_n_2), .B (out1[40]), .C
       (n_38), .Y (sll_426_30_n_5));
  NOR2X1 sll_426_30_g376(.A (sll_426_30_n_2), .B (n_38), .Y
       (sll_426_30_n_4));
  NOR2BX1 sll_426_30_g377(.AN (sll_426_30_n_2), .B (n_38), .Y
       (sll_426_30_n_3));
  INVX1 sll_426_30_g378(.A (n_18), .Y (sll_426_30_n_2));
  INVX1 sll_426_30_g379(.A (out1[40]), .Y (sll_426_30_n_1));
endmodule


