`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:16:31 CST (Apr 24 2022 06:16:31 UTC)

module DFT_compute_gen_busy_r_1_0(in1, in2, in3, in4, out1);
  input in1, in2, in3, in4;
  output [2:0] out1;
  wire in1, in2, in3, in4;
  wire [2:0] out1;
  wire n_0;
  CLKINVX2 g24(.A (out1[0]), .Y (out1[1]));
  AOI21X4 g25(.A0 (in4), .A1 (n_0), .B0 (in3), .Y (out1[0]));
  NAND2BX1 g26(.AN (in3), .B (n_0), .Y (out1[2]));
  OAI21X4 g27(.A0 (in1), .A1 (in4), .B0 (in2), .Y (n_0));
endmodule


