`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:08:45 CST (Apr 24 2022 07:08:45 UTC)

module DFT_compute_Add_8U_6_4(in1, out1);
  input [7:0] in1;
  output [7:0] out1;
  wire [7:0] in1;
  wire [7:0] out1;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  assign out1[3] = in1[3];
  assign out1[4] = in1[4];
  assign out1[5] = in1[5];
  assign out1[6] = in1[6];
  assign out1[7] = in1[7];
endmodule


