`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:19:41 CST (Apr 24 2022 06:19:41 UTC)

module DFT_compute_N_Mux_8_2_1_0(in3, in2, ctrl1, out1);
  input [7:0] in3, in2;
  input ctrl1;
  output [7:0] out1;
  wire [7:0] in3, in2;
  wire ctrl1;
  wire [7:0] out1;
  wire n_41, n_42, n_44, n_45, n_47, n_48, n_50, n_51;
  wire n_53, n_54, n_56, n_57, n_59, n_60, n_62, n_63;
  OAI21X4 g27(.A0 (ctrl1), .A1 (n_41), .B0 (n_42), .Y (out1[7]));
  INVX3 g29(.A (in3[7]), .Y (n_41));
  NAND2X8 g28(.A (in2[7]), .B (ctrl1), .Y (n_42));
  OAI21X4 g241(.A0 (ctrl1), .A1 (n_44), .B0 (n_45), .Y (out1[3]));
  INVX3 g242(.A (in3[3]), .Y (n_44));
  NAND2X8 g243(.A (in2[3]), .B (ctrl1), .Y (n_45));
  OAI21X4 g244(.A0 (ctrl1), .A1 (n_47), .B0 (n_48), .Y (out1[2]));
  INVX3 g245(.A (in3[2]), .Y (n_47));
  NAND2X8 g246(.A (in2[2]), .B (ctrl1), .Y (n_48));
  OAI21X4 g247(.A0 (ctrl1), .A1 (n_50), .B0 (n_51), .Y (out1[6]));
  INVX3 g248(.A (in3[6]), .Y (n_50));
  NAND2X8 g249(.A (in2[6]), .B (ctrl1), .Y (n_51));
  OAI21X4 g250(.A0 (ctrl1), .A1 (n_53), .B0 (n_54), .Y (out1[4]));
  INVX3 g251(.A (in3[4]), .Y (n_53));
  NAND2X8 g252(.A (in2[4]), .B (ctrl1), .Y (n_54));
  OAI21X4 g253(.A0 (ctrl1), .A1 (n_56), .B0 (n_57), .Y (out1[0]));
  INVX3 g254(.A (in3[0]), .Y (n_56));
  NAND2X8 g255(.A (in2[0]), .B (ctrl1), .Y (n_57));
  OAI21X4 g256(.A0 (ctrl1), .A1 (n_59), .B0 (n_60), .Y (out1[5]));
  INVX3 g257(.A (in3[5]), .Y (n_59));
  NAND2X8 g258(.A (in2[5]), .B (ctrl1), .Y (n_60));
  OAI21X4 g259(.A0 (ctrl1), .A1 (n_62), .B0 (n_63), .Y (out1[1]));
  INVX3 g260(.A (in3[1]), .Y (n_62));
  NAND2X8 g261(.A (in2[1]), .B (ctrl1), .Y (n_63));
endmodule


