`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:25:15 CST (Apr 24 2022 03:25:15 UTC)

module DFT_compute_LeftShift_2Sx2U_5S_1(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire sll_21_36_n_0, sll_21_36_n_1, sll_21_36_n_2, sll_21_36_n_3,
       sll_21_36_n_4;
  assign out1[4] = in2[1];
  OAI21X1 sll_21_36_g62(.A0 (sll_21_36_n_1), .A1 (sll_21_36_n_4), .B0
       (sll_21_36_n_2), .Y (out1[3]));
  NOR2X1 sll_21_36_g63(.A (in1[1]), .B (sll_21_36_n_4), .Y (out1[1]));
  OAI21X1 sll_21_36_g64(.A0 (sll_21_36_n_1), .A1 (sll_21_36_n_3), .B0
       (sll_21_36_n_2), .Y (out1[2]));
  NOR2X1 sll_21_36_g65(.A (in1[1]), .B (sll_21_36_n_3), .Y (out1[0]));
  MXI2X1 sll_21_36_g66(.A (in2[1]), .B (in2[0]), .S0 (in1[0]), .Y
       (sll_21_36_n_4));
  NAND2X1 sll_21_36_g67(.A (in2[0]), .B (sll_21_36_n_0), .Y
       (sll_21_36_n_3));
  NAND2X1 sll_21_36_g68(.A (in2[1]), .B (sll_21_36_n_1), .Y
       (sll_21_36_n_2));
  INVX1 sll_21_36_g69(.A (in1[1]), .Y (sll_21_36_n_1));
  INVX1 sll_21_36_g70(.A (in1[0]), .Y (sll_21_36_n_0));
endmodule


