`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:19:00 CST (Apr 24 2022 03:19:00 UTC)

module DFT_compute_LessThan_3Ux4U_1U_4(in2, in1, out1);
  input [2:0] in2;
  input [3:0] in1;
  output out1;
  wire [2:0] in2;
  wire [3:0] in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5;
  AOI32X1 gt_21_21_g97(.A0 (gt_21_21_n_3), .A1 (gt_21_21_n_0), .A2
       (gt_21_21_n_5), .B0 (in2[2]), .B1 (gt_21_21_n_2), .Y (out1));
  OAI21X1 gt_21_21_g98(.A0 (in1[1]), .A1 (gt_21_21_n_1), .B0
       (gt_21_21_n_4), .Y (gt_21_21_n_5));
  OAI2BB1X1 gt_21_21_g99(.A0N (in1[1]), .A1N (gt_21_21_n_1), .B0
       (in2[1]), .Y (gt_21_21_n_4));
  NAND2BXL gt_21_21_g100(.AN (in2[2]), .B (in1[2]), .Y (gt_21_21_n_3));
  NOR2X1 gt_21_21_g101(.A (in1[3]), .B (in1[2]), .Y (gt_21_21_n_2));
  NOR2BX1 gt_21_21_g102(.AN (in1[0]), .B (in2[0]), .Y (gt_21_21_n_1));
  INVX1 gt_21_21_g103(.A (in1[3]), .Y (gt_21_21_n_0));
endmodule


