`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 11:18:59 CST (Apr 24 2022 03:18:59 UTC)

module DFT_compute_LeftShift_2Sx2U_5S_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire sll_21_36_n_0, sll_21_36_n_1, sll_21_36_n_2;
  assign out1[4] = in2[1];
  OAI2BB1X1 sll_21_36_g62(.A0N (in1[1]), .A1N (sll_21_36_n_2), .B0
       (sll_21_36_n_0), .Y (out1[3]));
  NOR2BX1 sll_21_36_g63(.AN (sll_21_36_n_2), .B (in1[1]), .Y (out1[1]));
  OAI2BB1X1 sll_21_36_g64(.A0N (in1[1]), .A1N (sll_21_36_n_1), .B0
       (sll_21_36_n_0), .Y (out1[2]));
  NOR2BX1 sll_21_36_g65(.AN (sll_21_36_n_1), .B (in1[1]), .Y (out1[0]));
  MX2XL sll_21_36_g66(.A (in2[1]), .B (in2[0]), .S0 (in1[0]), .Y
       (sll_21_36_n_2));
  NOR2BX1 sll_21_36_g67(.AN (in2[0]), .B (in1[0]), .Y (sll_21_36_n_1));
  NAND2BX1 sll_21_36_g68(.AN (in1[1]), .B (in2[1]), .Y (sll_21_36_n_0));
endmodule


