`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:16:39 CST (Apr 24 2022 06:16:39 UTC)

module DFT_compute_N_Muxb_1_2_3_0(in3, in2, ctrl1, out1);
  input in3, in2, ctrl1;
  output out1;
  wire in3, in2, ctrl1;
  wire out1;
  wire n_6, n_7;
  OAI21X4 g27(.A0 (ctrl1), .A1 (n_6), .B0 (n_7), .Y (out1));
  INVX3 g31(.A (in3), .Y (n_6));
  NAND2X8 g32(.A (in2), .B (ctrl1), .Y (n_7));
endmodule


