`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:14:06 CST (Apr 24 2022 07:14:06 UTC)

module DFT_compute_entirecomputation_0(in1, out1);
  input [1:0] in1;
  output [47:0] out1;
  wire [1:0] in1;
  wire [47:0] out1;
  wire n_23, n_28, n_34;
  assign out1[0] = 1'b0;
  assign out1[1] = 1'b0;
  assign out1[2] = 1'b0;
  assign out1[3] = 1'b0;
  assign out1[4] = 1'b0;
  assign out1[5] = 1'b0;
  assign out1[6] = 1'b0;
  assign out1[7] = 1'b0;
  assign out1[8] = 1'b0;
  assign out1[9] = 1'b0;
  assign out1[10] = 1'b0;
  assign out1[11] = 1'b0;
  assign out1[12] = 1'b0;
  assign out1[13] = 1'b0;
  assign out1[14] = 1'b0;
  assign out1[15] = 1'b0;
  assign out1[16] = 1'b0;
  assign out1[17] = 1'b0;
  assign out1[18] = 1'b0;
  assign out1[19] = 1'b0;
  assign out1[20] = 1'b0;
  assign out1[21] = 1'b0;
  assign out1[22] = 1'b0;
  assign out1[25] = out1[40];
  assign out1[26] = out1[40];
  assign out1[27] = out1[40];
  assign out1[28] = out1[40];
  assign out1[29] = out1[40];
  assign out1[31] = 1'b0;
  assign out1[32] = out1[41];
  assign out1[33] = out1[42];
  assign out1[34] = out1[43];
  assign out1[35] = 1'b0;
  assign out1[36] = 1'b0;
  assign out1[37] = 1'b0;
  assign out1[38] = 1'b0;
  assign out1[39] = 1'b0;
  assign out1[44] = 1'b0;
  assign out1[45] = 1'b0;
  assign out1[46] = 1'b0;
  assign out1[47] = 1'b0;
  NOR2X2 g1058(.A (in1[1]), .B (out1[23]), .Y (out1[41]));
  NOR2X2 g1060(.A (in1[0]), .B (n_34), .Y (out1[42]));
  CLKINVX6 fopt1065(.A (in1[0]), .Y (out1[23]));
  NAND2X8 g19(.A (in1[1]), .B (in1[0]), .Y (n_23));
  OAI21X4 g15(.A0 (in1[0]), .A1 (in1[1]), .B0 (n_23), .Y (out1[24]));
  INVX1 g11(.A (n_28), .Y (out1[30]));
  NOR2X2 g12(.A (in1[1]), .B (in1[0]), .Y (n_28));
  NOR2X6 g13(.A (in1[1]), .B (in1[0]), .Y (out1[40]));
  NOR2X2 g1071(.A (out1[23]), .B (n_34), .Y (out1[43]));
  CLKINVX4 fopt(.A (in1[1]), .Y (n_34));
endmodule


