`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:21:57 CST (Apr 24 2022 07:21:57 UTC)

module DFT_compute_entirecomputation_4_1(in1, in2, in3, out1);
  input [22:0] in1;
  input [7:0] in2;
  input in3;
  output [31:0] out1;
  wire [22:0] in1;
  wire [7:0] in2;
  wire in3;
  wire [31:0] out1;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  assign out1[3] = in1[3];
  assign out1[4] = in1[4];
  assign out1[5] = in1[5];
  assign out1[6] = in1[6];
  assign out1[7] = in1[7];
  assign out1[8] = in1[8];
  assign out1[9] = in1[9];
  assign out1[10] = in1[10];
  assign out1[11] = in1[11];
  assign out1[12] = in1[12];
  assign out1[13] = in1[13];
  assign out1[14] = in1[14];
  assign out1[15] = in1[15];
  assign out1[16] = in1[16];
  assign out1[17] = in1[17];
  assign out1[18] = in1[18];
  assign out1[19] = in1[19];
  assign out1[20] = in1[20];
  assign out1[21] = in1[21];
  assign out1[22] = in1[22];
  assign out1[23] = in2[0];
  assign out1[24] = in2[1];
  assign out1[25] = in2[2];
  assign out1[26] = in2[3];
  assign out1[27] = in2[4];
  assign out1[28] = in2[5];
  assign out1[29] = in2[6];
  assign out1[30] = in2[7];
  assign out1[31] = in3;
endmodule


