`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 14:19:22 CST (Apr 24 2022 06:19:22 UTC)

module DFT_compute_LeftShift_2Sx2U_5S_0(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire n_0, n_3, n_4, n_29, n_33, n_34, n_35, n_37;
  wire n_38, n_39;
  assign out1[4] = in2[1];
  NOR3X2 g332(.A (in1[1]), .B (in1[0]), .C (n_0), .Y (out1[0]));
  NAND2X1 g335(.A (in2[0]), .B (in1[1]), .Y (n_4));
  NAND2X2 g334(.A (in2[0]), .B (in1[0]), .Y (n_3));
  INVX2 g337(.A (in2[0]), .Y (n_0));
  AOI21X1 g158(.A0 (n_3), .A1 (n_37), .B0 (in1[1]), .Y (out1[1]));
  OAI21X1 g161(.A0 (in1[0]), .A1 (n_4), .B0 (n_38), .Y (out1[2]));
  INVX1 g71(.A (in2[1]), .Y (n_29));
  NOR2X4 g48(.A (n_33), .B (n_34), .Y (n_35));
  CLKINVX6 g51(.A (in1[1]), .Y (n_33));
  CLKINVX8 g52(.A (in1[0]), .Y (n_34));
  NAND2X2 g49(.A (in2[1]), .B (n_34), .Y (n_37));
  NAND2X1 g50(.A (in2[1]), .B (n_33), .Y (n_38));
  OAI21X2 g33(.A0 (n_29), .A1 (n_35), .B0 (n_39), .Y (out1[3]));
  NAND3X8 g34(.A (in1[0]), .B (in1[1]), .C (in2[0]), .Y (n_39));
endmodule


