`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 24 2022 15:29:02 CST (Apr 24 2022 07:29:02 UTC)

module DFT_compute_Equal_1U_12_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR3BX1 g29(.AN (n_1), .B (in1[4]), .C (in1[3]), .Y (out1));
  NOR4X1 g30(.A (in1[6]), .B (in1[5]), .C (in1[0]), .D (n_0), .Y (n_1));
  OR2XL g31(.A (in1[2]), .B (in1[1]), .Y (n_0));
endmodule


